// <auto-generated />
using System;
using ControleFinanceiro.Infrastructure.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ControleFinanceiro.Infrastructure.EntityFramework.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260112174710_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ControleFinanceiro.Domain.Pessoas.Pessoa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Pessoas", (string)null);
                });

            modelBuilder.Entity("ControleFinanceiro.Domain.Transacoes.Categoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FinalidadeId")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FinalidadeId");

                    b.ToTable("Categorias", (string)null);
                });

            modelBuilder.Entity("ControleFinanceiro.Domain.Transacoes.Transacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("PessoaId")
                        .HasColumnType("uuid");

                    b.Property<int>("TipoTransacaoId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("PessoaId");

                    b.HasIndex("TipoTransacaoId");

                    b.ToTable("Transacoes", (string)null);
                });

            modelBuilder.Entity("ControleFinanceiro.Infrastructure.EntityFramework.Models.FinalidadeModel", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Finalidades", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 0,
                            Nome = "Despesa"
                        },
                        new
                        {
                            Id = 1,
                            Nome = "Receita"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Ambas"
                        });
                });

            modelBuilder.Entity("ControleFinanceiro.Infrastructure.EntityFramework.Models.TipoTransacaoModel", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TipoTransacoes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 0,
                            Nome = "Despesa"
                        },
                        new
                        {
                            Id = 1,
                            Nome = "Receita"
                        });
                });

            modelBuilder.Entity("ControleFinanceiro.Domain.Transacoes.Categoria", b =>
                {
                    b.HasOne("ControleFinanceiro.Infrastructure.EntityFramework.Models.FinalidadeModel", null)
                        .WithMany()
                        .HasForeignKey("FinalidadeId")
                        .IsRequired();
                });

            modelBuilder.Entity("ControleFinanceiro.Domain.Transacoes.Transacao", b =>
                {
                    b.HasOne("ControleFinanceiro.Domain.Pessoas.Pessoa", null)
                        .WithMany("Transacaos")
                        .HasForeignKey("PessoaId");

                    b.HasOne("ControleFinanceiro.Infrastructure.EntityFramework.Models.TipoTransacaoModel", null)
                        .WithMany()
                        .HasForeignKey("TipoTransacaoId")
                        .IsRequired();
                });

            modelBuilder.Entity("ControleFinanceiro.Domain.Pessoas.Pessoa", b =>
                {
                    b.Navigation("Transacaos");
                });
#pragma warning restore 612, 618
        }
    }
}
