FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src

COPY ControleFinanceiro.Application/*.csproj ControleFinanceiro.Application/
COPY ControleFinanceiro.Domain/*.csproj ControleFinanceiro.Domain/
COPY ControleFinanceiro.Infrastructure/*.csproj ControleFinanceiro.Infrastructure/

RUN dotnet restore ControleFinanceiro.Infrastructure/ControleFinanceiro.Infrastructure.csproj

COPY . .
WORKDIR /src/ControleFinanceiro.Infrastructure
RUN dotnet publish -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:10.0
WORKDIR /app

COPY --from=build /app/publish .

ENV ASPNETCORE_URLS=http://+:8080
EXPOSE 8080

ENTRYPOINT ["dotnet", "ControleFinanceiro.Infrastructure.dll"]

